### PR TITLE
1046. Last Stone Weight

### PR DESCRIPTION
**Pull request by Amisha2093**
## Added Leetcode easy problem: **1046. Last Stone Weight** in C++ language.

### CODE REVIEW

**Comment by Amisha2093** [comment]
Hi @SjxSubham,

Please review and accept my PR for the issue #11 under **hacktoberfest 24.**

**Comment by SjxSubham** [comment]
## Thank U for ur contribution
### Star the repo... HAppy Hacktober...

**Comment by SjxSubham** [comment]
#11 Closed

**Comment by Amisha2093** [comment]
Hi @SjxSubham,

Can you please add hacktoberfest tag to this PR. Thank you!

**Comment by SjxSubham** [comment]
Not needed actually, cause My Repo has already has `hacktoberfest-accepted` nd `hacktoberfest` tag already...

So Don't Worry it will be automatically accepted...

**Comment by Amisha2093** [comment]
okay, thank you!

**Pull request merged**
