### PR TITLE
731. My Calendar II

### PR DESCRIPTION
**Pull request by Brijeshthummar02**
issue #1

### CODE REVIEW

**Comment by SjxSubham** [comment]
### Hello @Brijeshthummar02, 
## Star the repo...   Thanks for ur Contribution...
## Happy Hacktober... 
#1  closed

**Comment by Brijeshthummar02** [comment]
@SjxSubham i have star the repo now you can merge it.

**Comment by Brijeshthummar02** [comment]
@SjxSubham

Adding unnecessary labels to someone’s PR, especially after they have provided a solution that has been reviewed and merged, goes against our community guidelines. This practice reflects a lack of guidance and consideration for contributors’ efforts and undermines the respect and collaboration we aim to foster.

In the long term, this behavior only detracts from your growth and reputation. While gaining stars, badges, or other short-term rewards may seem beneficial, focusing on personal gains over genuine contributions will not serve you well in the future. True success in open source comes from building meaningful, supportive relationships and contributing in ways that benefit the entire community.

**Comment by Brijeshthummar02** [comment]
To other contributors, I want to express my disappointment in this situation. This has been the worst experience I’ve had working on a repository. It’s disheartening to see that @SjxSubham  is more focused on personal gain than valuing the hard work of contributors. Such actions not only harm the community but also discourage collaboration and trust.

I will not be working with people who prioritize personal wealth over the efforts of others.

**Comment by SjxSubham** [comment]
> @SjxSubham
> 
> Adding unnecessary labels to someone’s PR, especially after they have provided a solution that has been reviewed and merged, goes against our community guidelines.  As maintainers, this practice reflects a lack of guidance and respect for contributors’ efforts, and it undermines the supportive and collaborative environment we aim to foster.
> 
> In the long term, this behavior only detracts from your growth and reputation. While gaining stars, badges, or other short-term rewards may seem beneficial, focusing on personal gains over genuine contributions will not serve you well in the future. True success in open source comes from building meaningful, supportive relationships and contributing in ways that benefit the entire community.

To get Your PR merged forcefully U hv given star and after getting merged, U removed the star.
And There's Issues section it's clearly mentioned that Add codes Only In Cpp, U have provided java solution.even  Though I have merged...!!!

And btw, U have already Gotten 4 PR merged for Hacktoberfest it's clearly visible on ur github profile ...
So u no need to worry , And Yah though I labeled it as invalid this Contribution will be still count in ur github profile... 


And if U want to get valid PR merged then add Code solution in Cpp with approach And I promise U this time I will Merge Ur PR and it will be valid contribution. Qnd yah It will accepted on that platform as Valid Contribution....

**Comment by Brijeshthummar02** [comment]
@SjxSubham when i created the pr have you told me that i want soln in cpp, without letting i know what you want you cannot mark any label, if you wanted the cpp soln you must say to me that this java soln won't be accepted as this whole repo is in cpp.

once the pr is merged you cannot label like invalid on somones pr. 
Also considering hacktoberfest i got notice of disqualification who's responsible for that.

**Comment by Brijeshthummar02** [comment]
@SjxSubham the work you shown is not at all acceptable.

**Comment by SjxSubham** [comment]
My fellow friend I have raised an issue right ... 
There U can see another Issue Which Has clearly mentioned That Code in Cpp ...

Even In the Repo readme it's clearly mentioned... 
And Yah U have Too much issue with that invalid label then Ok.. I Will remove that 

See this Issue On what date I have created

**Comment by Brijeshthummar02** [comment]
I have contributed to many large repositories, like Jenkins and others and I have never encountered this type of behavior. It's disappointing to see such practices here.

**Comment by SjxSubham** [comment]
> @SjxSubham when i created the pr have you told me that i want soln in cpp, without letting i know what you want you cannot mark any label, if you wanted the cpp soln you must say to me that this java soln won't be accepted as this whole repo is in cpp.
> 
> once the pr is merged you cannot label like invalid on somones pr. Also considering hacktoberfest i got notice of disqualification who's responsible for that.
> 
> Screenshot (67)

Okey I will remove the `invalid` tag... and By the way U no need to worry today is the last date of hacktoberfest. U will be not get disqualified...
This was warning only...

**Comment by Brijeshthummar02** [comment]
@SjxSubham , I have no issues or conflicts with your repository. My only concern is that you should avoid labeling solutions as "invalid" or "wontfix" when there is no error in the solution provided. If you had asked me to provide the solution in C++, I would have done so.

Additionally, you mentioned that stars on your repo are necessary and that I should star it before you would merge my PR. The decision to star a repository should depend on individual interest, not as a condition for merging contributions.

Thank you for understanding.

**Comment by SjxSubham** [comment]
and yah star it then i will merge I have said this condition because this will increase your contribution acceptance rate in hacktoberfest platform...
If u have remaining review more than 4 in hacktoberfest platform. then after 31october on which repo U have contributed and their repos platform will automatically  detect and prioritize that contributions first.
Cause some repo's have policy that add ur name on contrubutor list On that scenario Platform will detect U prefered contributions first.

**Pull request merged**
